export const RESOURCE_CATEGORIES = [
  "desktop-app",
  "deployment-runtime",
  "interface-tool",
  "orchestration",
  "training-quantization",
  "benchmark",
  "model-hub",
  "education",
  "community",
] as const

export type ResourceCategory = (typeof RESOURCE_CATEGORIES)[number]

export type Resource = Readonly<{
  id: string
  name: string
  owner: string
  description: string
  category: ResourceCategory
  access: string
  url: string
  repositoryUrl: string
  sourceUrls: readonly string[]
}>

export const resources = [
  {
    id: "lm-studio",
    name: "LM Studio",
    owner: "LM Studio",
    description: "Desktop application and local server for discovering, downloading, and running local language models on macOS, Windows, and Linux.",
    category: "desktop-app",
    access: "Free desktop download; application is proprietary; SDKs and selected components are open source",
    url: "https://lmstudio.ai/",
    repositoryUrl: "https://github.com/lmstudio-ai",
    sourceUrls: ["https://lmstudio.ai/", "https://lmstudio.ai/docs/", "https://github.com/lmstudio-ai"],
  },
  {
    id: "jan",
    name: "Jan",
    owner: "Menlo Research",
    description: "Local-first desktop AI application that runs open models on-device and can connect to remote model providers.",
    category: "desktop-app",
    access: "Open source; Apache License 2.0",
    url: "https://jan.ai/",
    repositoryUrl: "https://github.com/menloresearch/jan",
    sourceUrls: ["https://jan.ai/", "https://github.com/menloresearch/jan", "https://github.com/menloresearch/jan/blob/dev/LICENSE"],
  },
  {
    id: "gpt4all",
    name: "GPT4All",
    owner: "Nomic AI",
    description: "Desktop chat application and SDK ecosystem for running language models privately on consumer hardware.",
    category: "desktop-app",
    access: "Open source; MIT License; downloadable desktop application",
    url: "https://www.nomic.ai/gpt4all",
    repositoryUrl: "https://github.com/nomic-ai/gpt4all",
    sourceUrls: ["https://www.nomic.ai/gpt4all", "https://github.com/nomic-ai/gpt4all", "https://github.com/nomic-ai/gpt4all/blob/main/LICENSE.txt"],
  },
  {
    id: "llama-cpp",
    name: "llama.cpp",
    owner: "ggml-org",
    description: "C and C++ runtime for local and cloud LLM and VLM inference across CPU, Metal, CUDA, HIP, Vulkan, SYCL, and other backends.",
    category: "deployment-runtime",
    access: "Open source; MIT License",
    url: "https://github.com/ggml-org/llama.cpp",
    repositoryUrl: "https://github.com/ggml-org/llama.cpp",
    sourceUrls: ["https://github.com/ggml-org/llama.cpp", "https://github.com/ggml-org/llama.cpp/blob/master/LICENSE"],
  },
  {
    id: "ollama",
    name: "Ollama",
    owner: "Ollama",
    description: "Local model runner and server for building with open models on macOS, Windows, Linux, and Docker.",
    category: "deployment-runtime",
    access: "Public downloads; core repository is MIT-licensed",
    url: "https://ollama.com/",
    repositoryUrl: "https://github.com/ollama/ollama",
    sourceUrls: ["https://ollama.com/", "https://github.com/ollama/ollama", "https://github.com/ollama/ollama/blob/main/LICENSE"],
  },
  {
    id: "localai",
    name: "LocalAI",
    owner: "LocalAI team",
    description: "Composable local AI engine exposing OpenAI-, Anthropic-, and ElevenLabs-compatible APIs for language, vision, voice, image, and video models.",
    category: "deployment-runtime",
    access: "Open source; MIT License",
    url: "https://localai.io/",
    repositoryUrl: "https://github.com/mudler/LocalAI",
    sourceUrls: ["https://localai.io/", "https://github.com/mudler/LocalAI", "https://github.com/mudler/LocalAI/blob/master/LICENSE"],
  },
  {
    id: "vllm",
    name: "vLLM",
    owner: "vLLM project community",
    description: "High-throughput library and server for LLM inference with continuous batching, PagedAttention, quantization, distributed parallelism, and OpenAI-compatible APIs.",
    category: "deployment-runtime",
    access: "Open source; Apache License 2.0",
    url: "https://vllm.ai/",
    repositoryUrl: "https://github.com/vllm-project/vllm",
    sourceUrls: ["https://vllm.ai/", "https://github.com/vllm-project/vllm", "https://github.com/vllm-project/vllm/blob/main/LICENSE"],
  },
  {
    id: "sglang",
    name: "SGLang",
    owner: "SGLang project",
    description: "Serving framework for language and multimodal models with a high-performance runtime and frontend language for model programs.",
    category: "deployment-runtime",
    access: "Open source; Apache License 2.0",
    url: "https://www.sglang.io/",
    repositoryUrl: "https://github.com/sgl-project/sglang",
    sourceUrls: ["https://www.sglang.io/", "https://github.com/sgl-project/sglang", "https://github.com/sgl-project/sglang/blob/main/LICENSE"],
  },
  {
    id: "mlx-lm",
    name: "MLX LM",
    owner: "Apple Machine Learning Research",
    description: "Python package for generating text, quantizing, and fine-tuning large language models on Apple silicon with MLX.",
    category: "deployment-runtime",
    access: "Open source; MIT License",
    url: "https://github.com/ml-explore/mlx-lm",
    repositoryUrl: "https://github.com/ml-explore/mlx-lm",
    sourceUrls: ["https://github.com/ml-explore/mlx-lm", "https://github.com/ml-explore/mlx-lm/blob/main/LICENSE"],
  },
  {
    id: "exllamav3",
    name: "ExLlamaV3",
    owner: "turboderp",
    description: "GPU-focused inference library and quantization format for running transformer language models efficiently on NVIDIA hardware.",
    category: "deployment-runtime",
    access: "Open source; MIT License",
    url: "https://github.com/turboderp-org/exllamav3",
    repositoryUrl: "https://github.com/turboderp-org/exllamav3",
    sourceUrls: ["https://github.com/turboderp-org/exllamav3", "https://github.com/turboderp-org/exllamav3/blob/master/LICENSE"],
  },
  {
    id: "tensorrt-llm",
    name: "TensorRT-LLM",
    owner: "NVIDIA",
    description: "NVIDIA toolkit for optimizing and serving large language model inference with TensorRT on NVIDIA GPUs.",
    category: "deployment-runtime",
    access: "Open source; Apache License 2.0",
    url: "https://nvidia.github.io/TensorRT-LLM/",
    repositoryUrl: "https://github.com/NVIDIA/TensorRT-LLM",
    sourceUrls: ["https://nvidia.github.io/TensorRT-LLM/", "https://github.com/NVIDIA/TensorRT-LLM", "https://github.com/NVIDIA/TensorRT-LLM/blob/main/LICENSE"],
  },
  {
    id: "mlc-llm",
    name: "MLC LLM",
    owner: "MLC AI",
    description: "Machine-learning compilation runtime for deploying language models across GPUs, CPUs, browsers, and native applications.",
    category: "deployment-runtime",
    access: "Open source; Apache License 2.0",
    url: "https://llm.mlc.ai/",
    repositoryUrl: "https://github.com/mlc-ai/mlc-llm",
    sourceUrls: ["https://llm.mlc.ai/", "https://github.com/mlc-ai/mlc-llm", "https://github.com/mlc-ai/mlc-llm/blob/main/LICENSE"],
  },
  {
    id: "onnx-runtime-genai",
    name: "ONNX Runtime generate() API",
    owner: "Microsoft",
    description: "ONNX Runtime library providing generative-model loops, tokenization, sampling, KV-cache management, and model execution.",
    category: "deployment-runtime",
    access: "Open source; MIT License",
    url: "https://onnxruntime.ai/docs/genai/",
    repositoryUrl: "https://github.com/microsoft/onnxruntime-genai",
    sourceUrls: ["https://onnxruntime.ai/docs/genai/", "https://github.com/microsoft/onnxruntime-genai", "https://github.com/microsoft/onnxruntime-genai/blob/main/LICENSE"],
  },
  {
    id: "koboldcpp",
    name: "KoboldCpp",
    owner: "LostRuins",
    description: "Single-binary local inference server and interface built on llama.cpp with text-generation and multimodal features.",
    category: "deployment-runtime",
    access: "Open source; AGPL-3.0 License",
    url: "https://github.com/LostRuins/koboldcpp",
    repositoryUrl: "https://github.com/LostRuins/koboldcpp",
    sourceUrls: ["https://github.com/LostRuins/koboldcpp", "https://github.com/LostRuins/koboldcpp/blob/concedo/LICENSE.md"],
  },
  {
    id: "tabbyapi",
    name: "TabbyAPI",
    owner: "theroyallab",
    description: "OpenAI-compatible web server for ExLlamaV2 and ExLlamaV3 model inference.",
    category: "deployment-runtime",
    access: "Open source; AGPL-3.0 License",
    url: "https://github.com/theroyallab/tabbyAPI",
    repositoryUrl: "https://github.com/theroyallab/tabbyAPI",
    sourceUrls: ["https://github.com/theroyallab/tabbyAPI", "https://github.com/theroyallab/tabbyAPI/blob/main/LICENSE"],
  },
  {
    id: "mlx",
    name: "MLX",
    owner: "Apple Machine Learning Research",
    description: "Array framework for machine learning research on Apple silicon with unified memory and composable transformations.",
    category: "deployment-runtime",
    access: "Open source; MIT License",
    url: "https://ml-explore.github.io/mlx/",
    repositoryUrl: "https://github.com/ml-explore/mlx",
    sourceUrls: ["https://ml-explore.github.io/mlx/", "https://github.com/ml-explore/mlx", "https://github.com/ml-explore/mlx/blob/main/LICENSE"],
  },
  {
    id: "whisper-cpp",
    name: "whisper.cpp",
    owner: "ggml-org",
    description: "High-performance C and C++ implementation of OpenAI Whisper speech recognition for local inference.",
    category: "deployment-runtime",
    access: "Open source; MIT License",
    url: "https://github.com/ggml-org/whisper.cpp",
    repositoryUrl: "https://github.com/ggml-org/whisper.cpp",
    sourceUrls: ["https://github.com/ggml-org/whisper.cpp", "https://github.com/ggml-org/whisper.cpp/blob/master/LICENSE"],
  },
  {
    id: "llamafile",
    name: "llamafile",
    owner: "Mozilla Builders",
    description: "Packages model weights and a llama.cpp-based runtime into portable executables for local model distribution and execution.",
    category: "deployment-runtime",
    access: "Open source; Apache License 2.0",
    url: "https://mozilla-ai.github.io/llamafile/",
    repositoryUrl: "https://github.com/Mozilla-Ocho/llamafile",
    sourceUrls: ["https://mozilla-ai.github.io/llamafile/", "https://github.com/Mozilla-Ocho/llamafile", "https://github.com/Mozilla-Ocho/llamafile/blob/main/LICENSE"],
  },
  {
    id: "hipfire",
    name: "hipfire",
    owner: "warpfront",
    description: "Rust and HIP inference engine for running language models on AMD RDNA and CDNA GPUs with an OpenAI-compatible server.",
    category: "deployment-runtime",
    access: "Open source; Apache License 2.0, with identified files retaining MIT License notices",
    url: "https://github.com/warpfront/hipfire",
    repositoryUrl: "https://github.com/warpfront/hipfire",
    sourceUrls: ["https://github.com/warpfront/hipfire", "https://raw.githubusercontent.com/warpfront/hipfire/master/LICENSE", "https://github.com/warpfront/hipfire/blob/master/LICENSE-APACHE"],
  },
  {
    id: "lucebox",
    name: "Lucebox",
    owner: "Luce-Org",
    description: "Speculative-inference server for heterogeneous machines and consumer NVIDIA and AMD GPUs, with custom kernels and OpenAI-compatible serving.",
    category: "deployment-runtime",
    access: "Open source; Apache License 2.0",
    url: "https://www.lucebox.com/",
    repositoryUrl: "https://github.com/Luce-Org/lucebox",
    sourceUrls: ["https://www.lucebox.com/", "https://github.com/Luce-Org/lucebox", "https://github.com/Luce-Org/lucebox/blob/main/LICENSE"],
  },
  {
    id: "openvino",
    name: "OpenVINO",
    owner: "Intel",
    description: "Toolkit for optimizing and running AI inference across Intel CPUs, GPUs, and NPUs, including generative-model workloads.",
    category: "deployment-runtime",
    access: "Open source; Apache License 2.0",
    url: "https://docs.openvino.ai/",
    repositoryUrl: "https://github.com/openvinotoolkit/openvino",
    sourceUrls: ["https://docs.openvino.ai/", "https://github.com/openvinotoolkit/openvino", "https://github.com/openvinotoolkit/openvino/blob/master/LICENSE"],
  },
  {
    id: "executorch",
    name: "ExecuTorch",
    owner: "PyTorch Foundation",
    description: "On-device AI runtime and deployment stack for executing PyTorch models across mobile, embedded, and edge hardware.",
    category: "deployment-runtime",
    access: "Open source; BSD 3-Clause License",
    url: "https://pytorch.org/executorch/",
    repositoryUrl: "https://github.com/pytorch/executorch",
    sourceUrls: ["https://pytorch.org/executorch/", "https://github.com/pytorch/executorch", "https://github.com/pytorch/executorch/blob/main/LICENSE"],
  },
  {
    id: "open-webui",
    name: "Open WebUI",
    owner: "Open WebUI",
    description: "Self-hosted web interface for local Ollama models and OpenAI-compatible APIs, with model, agent, tool, RAG, and multi-user features.",
    category: "interface-tool",
    access: "Source available under the Open WebUI license; enterprise plans also offered",
    url: "https://openwebui.com/",
    repositoryUrl: "https://github.com/open-webui/open-webui",
    sourceUrls: ["https://docs.openwebui.com/", "https://github.com/open-webui/open-webui", "https://github.com/open-webui/open-webui/blob/main/LICENSE"],
  },
  {
    id: "anythingllm",
    name: "AnythingLLM",
    owner: "Mintplex Labs",
    description: "All-in-one desktop and self-hosted application for chatting with documents, using agents, and connecting local or remote models.",
    category: "interface-tool",
    access: "Open source; MIT License; desktop and self-hosted distributions",
    url: "https://anythingllm.com/",
    repositoryUrl: "https://github.com/Mintplex-Labs/anything-llm",
    sourceUrls: ["https://anythingllm.com/", "https://github.com/Mintplex-Labs/anything-llm", "https://github.com/Mintplex-Labs/anything-llm/blob/master/LICENSE"],
  },
  {
    id: "librechat",
    name: "LibreChat",
    owner: "LibreChat community",
    description: "Self-hosted multi-provider AI chat platform supporting agents, tools, model endpoints, and local inference servers.",
    category: "interface-tool",
    access: "Open source; MIT License",
    url: "https://www.librechat.ai/",
    repositoryUrl: "https://github.com/danny-avila/LibreChat",
    sourceUrls: ["https://www.librechat.ai/", "https://github.com/danny-avila/LibreChat", "https://github.com/danny-avila/LibreChat/blob/main/LICENSE"],
  },
  {
    id: "text-generation-webui",
    name: "text-generation-webui",
    owner: "oobabooga",
    description: "Gradio web interface for running and experimenting with local text-generation models through multiple loaders.",
    category: "interface-tool",
    access: "Open source; AGPL-3.0 License",
    url: "https://github.com/oobabooga/text-generation-webui",
    repositoryUrl: "https://github.com/oobabooga/text-generation-webui",
    sourceUrls: ["https://github.com/oobabooga/text-generation-webui", "https://github.com/oobabooga/text-generation-webui/blob/main/LICENSE"],
  },
  {
    id: "llama-swap",
    name: "llama-swap",
    owner: "mostlygeek",
    description: "Lightweight proxy that starts and stops local model servers on demand and exposes an OpenAI-compatible endpoint.",
    category: "orchestration",
    access: "Open source; MIT License",
    url: "https://github.com/mostlygeek/llama-swap",
    repositoryUrl: "https://github.com/mostlygeek/llama-swap",
    sourceUrls: ["https://github.com/mostlygeek/llama-swap", "https://github.com/mostlygeek/llama-swap/blob/main/LICENSE"],
  },
  {
    id: "llm-d",
    name: "llm-d",
    owner: "llm-d project",
    description: "Kubernetes-native distributed inference serving stack for large language models, built around vLLM and intelligent scheduling.",
    category: "orchestration",
    access: "Open source; Apache License 2.0",
    url: "https://llm-d.ai/",
    repositoryUrl: "https://github.com/llm-d/llm-d",
    sourceUrls: ["https://llm-d.ai/", "https://github.com/llm-d/llm-d", "https://github.com/llm-d/llm-d/blob/main/LICENSE"],
  },
  {
    id: "gpustack",
    name: "GPUStack",
    owner: "GPUStack",
    description: "Open-source platform for managing GPU clusters and deploying model inference services across heterogeneous hardware.",
    category: "orchestration",
    access: "Open source; Apache License 2.0",
    url: "https://gpustack.ai/",
    repositoryUrl: "https://github.com/gpustack/gpustack",
    sourceUrls: ["https://gpustack.ai/", "https://github.com/gpustack/gpustack", "https://github.com/gpustack/gpustack/blob/main/LICENSE"],
  },
  {
    id: "unsloth",
    name: "Unsloth",
    owner: "Unsloth AI",
    description: "Toolkit for memory-efficient fine-tuning and reinforcement learning of open language models.",
    category: "training-quantization",
    access: "Open source; Apache License 2.0",
    url: "https://unsloth.ai/",
    repositoryUrl: "https://github.com/unslothai/unsloth",
    sourceUrls: ["https://unsloth.ai/", "https://github.com/unslothai/unsloth", "https://github.com/unslothai/unsloth/blob/main/LICENSE"],
  },
  {
    id: "auto-round",
    name: "AutoRound",
    owner: "Intel",
    description: "Weight-only quantization toolkit for compressing language and multimodal models with low tuning cost.",
    category: "training-quantization",
    access: "Open source; Apache License 2.0",
    url: "https://github.com/intel/auto-round",
    repositoryUrl: "https://github.com/intel/auto-round",
    sourceUrls: ["https://github.com/intel/auto-round", "https://github.com/intel/auto-round/blob/main/LICENSE"],
  },
  {
    id: "bitsandbytes",
    name: "bitsandbytes",
    owner: "bitsandbytes-foundation",
    description: "Library providing k-bit optimizers, matrix multiplication, and quantization primitives for PyTorch models.",
    category: "training-quantization",
    access: "Open source; MIT License",
    url: "https://huggingface.co/docs/bitsandbytes/",
    repositoryUrl: "https://github.com/bitsandbytes-foundation/bitsandbytes",
    sourceUrls: ["https://huggingface.co/docs/bitsandbytes/", "https://github.com/bitsandbytes-foundation/bitsandbytes", "https://github.com/bitsandbytes-foundation/bitsandbytes/blob/main/LICENSE"],
  },
  {
    id: "gptqmodel",
    name: "GPTQModel",
    owner: "ModelCloud",
    description: "Model quantization and inference library implementing GPTQ-family post-training quantization across multiple backends.",
    category: "training-quantization",
    access: "Open source; Apache License 2.0",
    url: "https://github.com/ModelCloud/GPTQModel",
    repositoryUrl: "https://github.com/ModelCloud/GPTQModel",
    sourceUrls: ["https://github.com/ModelCloud/GPTQModel", "https://github.com/ModelCloud/GPTQModel/blob/main/LICENSE"],
  },
  {
    id: "llama-factory",
    name: "LLaMA-Factory",
    owner: "hiyouga",
    description: "Unified framework for fine-tuning language and multimodal models with scalable training methods and a browser-based interface.",
    category: "training-quantization",
    access: "Open source; Apache License 2.0",
    url: "https://llamafactory.readthedocs.io/",
    repositoryUrl: "https://github.com/hiyouga/LLaMA-Factory",
    sourceUrls: ["https://llamafactory.readthedocs.io/", "https://github.com/hiyouga/LLaMA-Factory", "https://github.com/hiyouga/LLaMA-Factory/blob/main/LICENSE"],
  },
  {
    id: "spark-arena",
    name: "Spark Arena",
    owner: "Spark Arena community",
    description: "Public leaderboard comparing real LLM inference benchmarks, runtimes, recipes, and configurations on NVIDIA DGX Spark hardware.",
    category: "benchmark",
    access: "Public website; community benchmark submissions; website license not stated",
    url: "https://spark-arena.com/",
    repositoryUrl: "https://github.com/spark-arena/sparkrun",
    sourceUrls: ["https://spark-arena.com/", "https://github.com/spark-arena/sparkrun"],
  },
  {
    id: "localmaxxing",
    name: "LocalMaxxing",
    owner: "LocalMaxxing",
    description: "Community platform for local-LLM speed tests and quality benchmarks across models, hardware, engines, and quantizations.",
    category: "benchmark",
    access: "Public leaderboard; GitHub sign-in and API key required to submit; official CLI is MIT-licensed",
    url: "https://www.localmaxxing.com/en",
    repositoryUrl: "https://github.com/LottoLottoLotto/localmaxxing-cli",
    sourceUrls: ["https://www.localmaxxing.com/en", "https://github.com/LottoLottoLotto/localmaxxing-cli", "https://raw.githubusercontent.com/LottoLottoLotto/localmaxxing-cli/main/LICENSE"],
  },
  {
    id: "llama-bench",
    name: "llama-bench",
    owner: "ggml-org",
    description: "Benchmark executable included with llama.cpp for measuring model load, prompt processing, and token-generation performance.",
    category: "benchmark",
    access: "Open source as part of llama.cpp; MIT License",
    url: "https://github.com/ggml-org/llama.cpp/tree/master/tools/llama-bench",
    repositoryUrl: "https://github.com/ggml-org/llama.cpp",
    sourceUrls: ["https://github.com/ggml-org/llama.cpp/tree/master/tools/llama-bench", "https://github.com/ggml-org/llama.cpp/blob/master/LICENSE"],
  },
  {
    id: "genai-perf",
    name: "GenAI-Perf",
    owner: "NVIDIA",
    description: "Command-line benchmarking application for measuring throughput and latency of generative-AI inference services.",
    category: "benchmark",
    access: "Open source; Apache License 2.0",
    url: "https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/perf_analyzer/genai-perf/README.html",
    repositoryUrl: "https://github.com/triton-inference-server/perf_analyzer",
    sourceUrls: ["https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/perf_analyzer/genai-perf/README.html", "https://github.com/triton-inference-server/perf_analyzer", "https://github.com/triton-inference-server/perf_analyzer/blob/main/LICENSE"],
  },
  {
    id: "harbor",
    name: "Harbor",
    owner: "Laude Institute",
    description: "Framework for running and evaluating agents in containerized task environments, including Terminal-Bench.",
    category: "benchmark",
    access: "Open source; Apache License 2.0",
    url: "https://harborframework.com/",
    repositoryUrl: "https://github.com/laude-institute/harbor",
    sourceUrls: ["https://harborframework.com/", "https://github.com/laude-institute/harbor", "https://github.com/laude-institute/harbor/blob/main/LICENSE"],
  },
  {
    id: "terminal-bench",
    name: "Terminal-Bench",
    owner: "Laude Institute",
    description: "Benchmark dataset and harness for evaluating AI agents on real terminal tasks in isolated environments.",
    category: "benchmark",
    access: "Open source; Apache License 2.0",
    url: "https://www.tbench.ai/",
    repositoryUrl: "https://github.com/laude-institute/terminal-bench",
    sourceUrls: ["https://www.tbench.ai/", "https://github.com/laude-institute/terminal-bench", "https://github.com/laude-institute/terminal-bench/blob/main/LICENSE"],
  },
  {
    id: "open-llm-leaderboard",
    name: "Open LLM Leaderboard",
    owner: "Hugging Face",
    description: "Open evaluation platform and reproducible harness for comparing language models on standardized benchmarks.",
    category: "benchmark",
    access: "Public leaderboard; evaluation code is open source under Apache License 2.0",
    url: "https://huggingface.co/spaces/open-llm-leaderboard/open_llm_leaderboard",
    repositoryUrl: "https://github.com/huggingface/open_llm_leaderboard",
    sourceUrls: ["https://huggingface.co/spaces/open-llm-leaderboard/open_llm_leaderboard", "https://github.com/huggingface/open_llm_leaderboard", "https://github.com/huggingface/open_llm_leaderboard/blob/main/LICENSE"],
  },
  {
    id: "lm-evaluation-harness",
    name: "Language Model Evaluation Harness",
    owner: "EleutherAI",
    description: "Unified framework for evaluating local and hosted language models across a large collection of reproducible academic benchmark tasks.",
    category: "benchmark",
    access: "Open source; MIT License",
    url: "https://github.com/EleutherAI/lm-evaluation-harness",
    repositoryUrl: "https://github.com/EleutherAI/lm-evaluation-harness",
    sourceUrls: ["https://github.com/EleutherAI/lm-evaluation-harness", "https://github.com/EleutherAI/lm-evaluation-harness/blob/main/LICENSE.md", "https://doi.org/10.5281/zenodo.10256836"],
  },
  {
    id: "swe-bench",
    name: "SWE-bench",
    owner: "SWE-bench team",
    description: "Dataset and reproducible Docker evaluation harness for measuring whether language-model agents can resolve real-world software issues.",
    category: "benchmark",
    access: "Open source; MIT License",
    url: "https://swebench.com/",
    repositoryUrl: "https://github.com/SWE-bench/SWE-bench",
    sourceUrls: ["https://swebench.com/", "https://github.com/SWE-bench/SWE-bench", "https://github.com/SWE-bench/SWE-bench/blob/main/LICENSE"],
  },
  {
    id: "swe-bench-live",
    name: "SWE-bench Live",
    owner: "SWE-bench Live team",
    description: "Continuously updated software-engineering agent benchmark with Lite, Verified, Windows, and multilingual language-specific leaderboards backed by public submission artifacts.",
    category: "benchmark",
    access: "Public leaderboard and submissions; evaluation repository is open source under the MIT License",
    url: "https://swe-bench-live.github.io/",
    repositoryUrl: "https://github.com/SWE-bench-Live/SWE-bench-Live",
    sourceUrls: ["https://swe-bench-live.github.io/", "https://github.com/SWE-bench-Live/SWE-bench-Live", "https://github.com/SWE-bench-Live/SWE-bench-Live/blob/main/LICENSE", "https://github.com/SWE-bench-Live/submission"],
  },
  {
    id: "livecodebench",
    name: "LiveCodeBench",
    owner: "LiveCodeBench team",
    description: "Contamination-resistant benchmark and evaluation code for measuring language-model code-generation ability with continuously collected programming problems.",
    category: "benchmark",
    access: "Open source; MIT License",
    url: "https://livecodebench.github.io/",
    repositoryUrl: "https://github.com/LiveCodeBench/LiveCodeBench",
    sourceUrls: ["https://livecodebench.github.io/", "https://github.com/LiveCodeBench/LiveCodeBench", "https://github.com/LiveCodeBench/LiveCodeBench/blob/main/LICENSE"],
  },
  {
    id: "local-inference",
    name: "Local Inference",
    owner: "Local Inference project",
    description: "Open initiative producing small, task-specific machine-learning models distributed in ONNX format for local use on devices, servers, and browsers.",
    category: "model-hub",
    access: "Open source; Apache License 2.0 for models, code, tooling, and specifications",
    url: "https://github.com/localinference",
    repositoryUrl: "https://github.com/localinference/.github",
    sourceUrls: ["https://github.com/localinference", "https://raw.githubusercontent.com/localinference/.github/main/profile/README.md"],
  },
  {
    id: "hugging-face-hub",
    name: "Hugging Face Hub",
    owner: "Hugging Face",
    description: "Git-based platform for discovering, versioning, sharing, and collaborating on models, datasets, and ML applications.",
    category: "model-hub",
    access: "Public and private repositories; free public access with paid Pro, Team, and Enterprise plans; individual artifacts retain their own licenses and gating",
    url: "https://huggingface.co/",
    repositoryUrl: "https://github.com/huggingface/huggingface_hub",
    sourceUrls: ["https://huggingface.co/docs/hub/index", "https://github.com/huggingface/huggingface_hub"],
  },
  {
    id: "modelscope",
    name: "ModelScope",
    owner: "Alibaba Cloud",
    description: "Model-as-a-Service ecosystem and hubs for discovering, versioning, downloading, running, fine-tuning, and evaluating models and datasets.",
    category: "model-hub",
    access: "Many models are publicly downloadable; model licenses vary; core SDK is Apache License 2.0",
    url: "https://modelscope.cn/",
    repositoryUrl: "https://github.com/modelscope/modelscope",
    sourceUrls: ["https://modelscope.cn/", "https://github.com/modelscope/modelscope", "https://github.com/modelscope/modelscope/blob/master/LICENSE"],
  },
  {
    id: "hugging-face-llm-course",
    name: "Hugging Face LLM Course",
    owner: "Hugging Face",
    description: "Free course covering transformer models, Hugging Face libraries, fine-tuning, datasets, tokenizers, demos, and advanced LLM topics.",
    category: "education",
    access: "Free public course; course repository is Apache License 2.0",
    url: "https://huggingface.co/learn/llm-course/",
    repositoryUrl: "https://github.com/huggingface/course",
    sourceUrls: ["https://huggingface.co/learn/llm-course/", "https://github.com/huggingface/course", "https://github.com/huggingface/course/blob/main/LICENSE"],
  },
  {
    id: "awesome-local-ai",
    name: "Awesome Local AI",
    owner: "Jan community",
    description: "Curated directory of open-source and local AI inference engines, interfaces, platforms, developer tools, agents, training projects, leaderboards, and communities.",
    category: "community",
    access: "Public GitHub resource; Creative Commons Attribution 4.0 International",
    url: "https://github.com/janhq/awesome-local-ai",
    repositoryUrl: "https://github.com/janhq/awesome-local-ai",
    sourceUrls: ["https://github.com/janhq/awesome-local-ai", "https://github.com/janhq/awesome-local-ai/blob/main/LICENSE"],
  },
] as const satisfies readonly Resource[]
